#!/bin/sh

set -e

chown "$UID:$GID" /app /data/caddy /config/caddy

install -o "$UID" -g "$GID" -d \
    storage/cache \
    storage/formatter \
    storage/less \
    storage/locale \
    storage/logs \
    storage/sessions \
    storage/tmp \
    storage/views \
    public/assets/avatars

if [ -e 'storage/install.lock' ]; then
    echo "Already installed"
    install -o "$UID" -g "$GID" config.docker.php config.php
else
    echo "Installing"

    rm -f config.php

    cfg=install.yml

    echo "debug: false" >> $cfg
    echo "baseUrl: ${FLARUM_URL:-http://localhost}" >> $cfg
    echo "databaseConfiguration:" >> $cfg
    echo "  driver: mysql" >> $cfg
    echo "  host: ${FLARUM_DB_HOST:-db}" >> $cfg
    echo "  database: ${FLARUM_DB_DATABASE:-flarum}" >> $cfg
    echo "  username: ${FLARUM_DB_USERNAME:-flarum}" >> $cfg
    echo "  password: ${FLARUM_DB_PASSWORD:-flarum}" >> $cfg
    echo "  prefix: ${FLARUM_DB_PREFIX}" >> $cfg
    echo "  port: ${FLARUM_DB_PORT:-3306}" >> $cfg
    echo "adminUser:" >> $cfg
    echo "  username: ${FLARUM_INSTALL_ADMIN_USERNAME}" >> $cfg
    echo "  password: ${FLARUM_INSTALL_ADMIN_PASSWORD}" >> $cfg
    echo "  email: ${FLARUM_INSTALL_ADMIN_EMAIL}" >> $cfg
    echo "settings:" >> $cfg
    echo "  forum_title: ${FLARUM_TITLE:-Flarum}" >> $cfg

    php flarum install -f $cfg

    rm $cfg

    install -o "$UID" -g "$GID" /dev/null storage/install.lock
fi

su-exec "$UID:$GID" frankenphp run --config /etc/caddy/Caddyfile --adapter caddyfile
